### ISSUE TITLE
Complile Error nedf_intWithUnit -> Current Master

### ISSUE THREAD

**Issue by scimbe** [inet-framework/inet#284]
Current Master shows me a compile error.

commit d375e4d008460a7cc712a84a572653c1a35f46bb was compileable. 
Did I miss anything?

Building...
inet/common/NedFunctions.cc
inet/common/NedFunctions.cc:214:8: error: ‘cNedValue’ does not name a type
 static cNedValue nedf_intWithUnit(cComponent *contextComponent, cNedValue argv[], int argc)
        ^
In file included from /home/martin/Dokumente/3rd/omnetpp/include/omnetpp/globals.h:21:0,
                 from /home/martin/Dokumente/3rd/omnetpp/include/omnetpp/cobjectfactory.h:20,
                 from /home/martin/Dokumente/3rd/omnetpp/include/omnetpp.h:30,
                 from inet/common/precompiled.h:28,
                 from inet/common/precompiled_release.h:1:
inet/common/NedFunctions.cc: In function ‘void inet::utils::{anonymous}::__onstartup_func_234()’:
inet/common/NedFunctions.cc:231:22: error: ‘nedf_intWithUnit’ was not declared in this scope
 Define_NED_Function2(nedf_intWithUnit,
                      ^
Makefile:1330: recipe for target '../out/gcc-release/src/inet/common/NedFunctions.o' failed

Best 
Martin 

PS: Don't check the line numbers, it might be shift in a way

**Comment by torokati44** [comment]
This NED function was just recently added. Take a look at commits made on
the 15th. There are some conditional definitions depending on a couple of
OMNeT++ version  macros, those might be the cause. Which OMNeT++ version do
you use? It certainly works with 5.3p2.

On Jan 19, 2018 17:16, "Martin Becke" <notifications@github.com> wrote:

Current Master shows me a compile error.

commit d375e4d
<https://github.com/inet-framework/inet/commit/d375e4d008460a7cc712a84a572653c1a35f46bb>
was compileable.
Did I miss anything?

Building...
inet/common/NedFunctions.cc
inet/common/NedFunctions.cc:214:8: error: ‘cNedValue’ does not name a type
static cNedValue nedf_intWithUnit(cComponent *contextComponent, cNedValue
argv[], int argc)
^
In file included from /home/martin/Dokumente/3rd/omnetpp/include/omnetpp/
globals.h:21:0,
from /home/martin/Dokumente/3rd/omnetpp/include/omnetpp/cobjectfactory.h:20,
from /home/martin/Dokumente/3rd/omnetpp/include/omnetpp.h:30,
from inet/common/precompiled.h:28,
from inet/common/precompiled_release.h:1:
inet/common/NedFunctions.cc: In function ‘void inet::utils::{anonymous}::__
onstartup_func_234()’:
inet/common/NedFunctions.cc:231:22: error: ‘nedf_intWithUnit’ was not
declared in this scope
Define_NED_Function2(nedf_intWithUnit,
^
Makefile:1330: recipe for target
'../out/gcc-release/src/inet/common/NedFunctions.o'
failed

Best
Martin

PS: Don't check the line numbers, it might be shift in a way

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/inet-framework/inet/issues/284>, or mute the thread

**Comment by scimbe** [comment]
Thanks for the hint. 5.2.1 caused the error.
Setup with 5.3p fixed the issue. 

Is there a default way to check this dependency next time on my own? 
Is there a version check (e.g. assert on lower version, etc) or any information in WHATSNEW I can use?

Thanks again! 
Best 
Martin

**Comment by torokati44** [comment]
Well, I think the intention was that it should work with 5.1 and 5.2 as well, that's why those version comparisons are there. But it looks like they need some slight adjustment. We'll take a look at it next week.

**Comment by scimbe** [comment]
Thanks for feedback. You can close this issue from my side.

**Comment by ZoltanBojthe** [comment]
Fixed
