### ISSUE TITLE
Compilation Failure: osgEarthUtil ObjectLocator has been deprecated - CoordinateSystem.cc

### ISSUE THREAD

**Issue by shef** [inet-framework/inet#314]
I'm trying to build inet framework with osgearth-2.9 (default package in ubuntu 18.04) and getting compilation error due to missing ObjectLocator header file:
```
inet/common/geometry/common/CoordinateSystem.cc:21:10: fatal error: osgEarthUtil/ObjectLocator: No such file or directory
 #include <osgEarthUtil/ObjectLocator>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Reference to the deprecated file is in CoordinateSystem.cc: https://github.com/inet-framework/inet/blob/6983a32a4fa1c29e88167eca16bc4c757d153113/src/inet/common/geometry/common/CoordinateSystem.cc#L21

Based on the osgearth commit history, the file was removed back in 2017. Here are two related commits:
```

commit 6d8a14031b547a3fbb762c6198558d4dc28f2340
Author: gwaldron <gwaldron@gmail.com>
Date:   Thu Nov 16 15:20:21 2017 -0500

    Remove deprecated or unused classes

commit c5f4f4db3e290f6cca311a3fa66838ba6aa2756e
Author: gwaldron <gwaldron@gmail.com>
Date:   Thu Jun 1 13:03:31 2017 -0400

    ObjectLocator (deprecated) confirm to OSG 356 API

```

**Comment by torokati44** [comment]
Thanks for reporting! We are aware of this problem, and there is a pending patch in the repo we just haven't fully tested yet.
You could try cherry-picking https://github.com/inet-framework/inet/commit/fccb335dfcb01e2890e4b39a8d65610f4010d6e9 and see if it helps. Please report any problems it might cause!
This should be included in the `master` and `integration` branches eventually.

**Comment by shef** [comment]
It get's too complicated to backport the diff into the latest stable version. However, I switched to the 3.99.3 and it gets built. Tried to run few examples - all worked. Closing the issue since it's already fixed :smiley:

**Comment by Bala272** [comment]
Thanks for the solution, but in my case I am unable to run examples in INET as it shows below error:
<!> Error: Cannot load library '../../../src//libINET.so': ../../../src//libINET.so: undefined symbol: _ZTIN3osg5GroupE

Could you please let me know the solution.
Note: My environment is Ubuntu 18.04 LTS, Omnet++ 5.4 and inet 3.99.3, and I got the same error in Omnet++ 5.3 also

**Comment by bourou01** [comment]
Bala272 please refer to this issue to resolve your linking error.
https://github.com/inet-framework/inet/issues/353
There is a patch to solve the linking error
