### ISSUE TITLE
examples/mobileipv6 example crashes

### ISSUE THREAD

**Issue by v44r** [inet-framework/inet#473]
xMIPv6 fails in inet-4.1.1. It used to work in 4.0.0 (well, more or less; it's always been finicky). Now the example in examples/mobileipv6 fails with

ASSERT: Condition 'list != nullptr' does not hold in function 'setDefaultOwner' at cownedobject.cc:123 -- at t=104.526573010702s, event #165966

Backtrace: 
(gdb) bt
#0  omnetpp::cRuntimeError::notifyEnvir (this=0x5555642196c0) at cexception.cc:260
#1  0x00007ffff7720ae0 in omnetpp::cRuntimeError::cRuntimeError (this=0x5555642196c0, msgformat=0x7ffff78888e8 "ASSERT: Condition '%s' does not hold in function '%s' at %s:%d") at cexception.cc:234
#2  0x00007ffff77646ac in omnetpp::cOwnedObject::setDefaultOwner (list=0x0) at cownedobject.cc:123
#3  0x00007ffff77848be in omnetpp::cSimulation::setContext (this=0x5555557448c0, p=0x0) at csimulation.cc:684
#4  0x00007ffff77b5529 in omnetpp::cContextSwitcher::cContextSwitcher (this=0x7fffffffc480, newContext=0x0) at util.cc:214
#5  0x00007ffff77b5593 in omnetpp::cMethodCallContextSwitcher::cMethodCallContextSwitcher (this=0x7fffffffc480, newContext=0x0) at util.cc:233
#6  0x00007ffff16edcd1 in inet::xMIPv6::initiateMipv6Protocol (this=0x0, ie=0x555557ee2260, CoA=...) at inet/networklayer/xmipv6/xMIPv6.cc:251
#7  0x00007ffff159340e in inet::Ipv6NeighbourDiscovery::makeTentativeAddressPermanent (this=0x555557d111e0, tentativeAddr=..., ie=0x555557ee2260) at inet/networklayer/icmpv6/Ipv6NeighbourDiscovery.cc:916
#8  0x00007ffff15930e8 in inet::Ipv6NeighbourDiscovery::processDadTimeout (this=0x555557d111e0, msg=0x5555630b3120) at inet/networklayer/icmpv6/Ipv6NeighbourDiscovery.cc:877
#9  0x00007ffff158d80b in inet::Ipv6NeighbourDiscovery::handleMessage (this=0x555557d111e0, msg=0x5555630b3120) at inet/networklayer/icmpv6/Ipv6NeighbourDiscovery.cc:168
#10 0x00007ffff7784846 in omnetpp::cSimulation::doMessageEvent (this=0x5555557448c0, msg=0x5555630b3120, module=0x555557d111e0) at csimulation.cc:669
#11 0x00007ffff77844ca in omnetpp::cSimulation::executeEvent (this=0x5555557448c0, event=0x5555630b3120) at csimulation.cc:611
#12 0x00007ffff7c91eb2 in omnetpp::qtenv::Qtenv::doRunSimulation (this=0x5555557405f0) at qtenv.cc:895
#13 0x00007ffff7c917aa in omnetpp::qtenv::Qtenv::runSimulation (this=0x5555557405f0, mode=omnetpp::qtenv::RUNMODE_FAST, until_time=..., until_eventnum=0, until_msg=0x0, until_module=0x0, stopOnMsgCancel=true) at qtenv.cc:745
#14 0x00007ffff7c1d76e in omnetpp::qtenv::MainWindow::runSimulation (this=0x55555798e000, runMode=omnetpp::qtenv::RUNMODE_FAST) at mainwindow.cc:497
#15 0x00007ffff7d0df77 in omnetpp::qtenv::MainWindow::on_actionFastRun_triggered (this=0x55555798e000) at mainwindow.h:97
#16 0x00007ffff7d0d839 in omnetpp::qtenv::MainWindow::qt_static_metacall (_o=0x55555798e000, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7fffffffcb00) at moc_mainwindow.cpp:295
#17 0x00007ffff7d0de34 in omnetpp::qtenv::MainWindow::qt_metacall (this=0x55555798e000, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7fffffffcb00) at moc_mainwindow.cpp:396
#18 0x00007ffff6238acd in QMetaObject::activate(QObject*, int, int, void**) () from /lib/libQt5Core.so.5
#19 0x00007ffff5a36eb3 in QAction::triggered(bool) () from /lib/libQt5Widgets.so.5
#20 0x00007ffff5a39644 in QAction::activate(QAction::ActionEvent) () from /lib/libQt5Widgets.so.5
#21 0x00007ffff5b3831d in ?? () from /lib/libQt5Widgets.so.5
#22 0x00007ffff5b38546 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /lib/libQt5Widgets.so.5
#23 0x00007ffff5c2dd6b in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /lib/libQt5Widgets.so.5
#24 0x00007ffff5a810e6 in QWidget::event(QEvent*) () from /lib/libQt5Widgets.so.5
#25 0x00007ffff5c2de15 in QToolButton::event(QEvent*) () from /lib/libQt5Widgets.so.5
#26 0x00007ffff5a3d4f5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#27 0x00007ffff5a46f8a in QApplication::notify(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#28 0x00007ffff620c9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/libQt5Core.so.5
#29 0x00007ffff5a4613b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /lib/libQt5Widgets.so.5
#30 0x00007ffff5a9d391 in ?? () from /lib/libQt5Widgets.so.5
#31 0x00007ffff5aa02d4 in ?? () from /lib/libQt5Widgets.so.5
#32 0x00007ffff5a3d4f5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#33 0x00007ffff5a46e11 in QApplication::notify(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#34 0x00007ffff620c9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/libQt5Core.so.5
#35 0x00007ffff65a8bf4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/libQt5Gui.so.5
#36 0x00007ffff65aa49b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/libQt5Gui.so.5
#37 0x00007ffff6584afc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Gui.so.5
#38 0x00007fffeeb8612c in ?? () from /lib/libQt5XcbQpa.so.5
#39 0x00007ffff49323fe in g_main_context_dispatch () from /lib/libglib-2.0.so.0
#40 0x00007ffff4934211 in ?? () from /lib/libglib-2.0.so.0
#41 0x00007ffff4934251 in g_main_context_iteration () from /lib/libglib-2.0.so.0
#42 0x00007ffff6264a03 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Core.so.5
#43 0x00007ffff620b4ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Core.so.5
#44 0x00007ffff6213326 in QCoreApplication::exec() () from /lib/libQt5Core.so.5
#45 0x00007ffff7c90fa4 in omnetpp::qtenv::Qtenv::doRun (this=0x5555557405f0) at qtenv.cc:638
#46 0x00007ffff7ee0024 in omnetpp::envir::EnvirBase::run (this=0x555555740600) at envirbase.cc:743
#47 0x00007ffff7edda56 in omnetpp::envir::EnvirBase::run (this=0x555555740600, argc=9, argv=0x7fffffffdf58, configobject=0x55555558b900) at envirbase.cc:354
#48 0x00007ffff7ed5a1c in omnetpp::envir::setupUserInterface (argc=9, argv=0x7fffffffdf58) at startup.cc:259
#49 0x00007ffff7ed6dec in omnetpp::envir::evMain (argc=9, argv=0x7fffffffdf58) at evmain.cc:33
#50 0x0000555555555159 in main (argc=9, argv=0x7fffffffdf58) at main.cc:31

**Comment by levy** [comment]
I can't reproduce this in the INET master branch (the upcoming 4.2 version) with OMNeT 5.5.1.

**Comment by v44r** [comment]
For me it still happens in current master as soon as MN associates with AP_1 (second ~104).

I bisected:

Last good commit: 86dca4b967443d50dccbd264bc528493ca04be7b (doesn't segfault)
First bad commit: 888e96100ef27c418b305e9281914717b7395b1c (segfaults as above)

(There are 4 or 5 commits in between, but they fail to compile with ‘INITSTAGE_NETWORK_LAYER_2’ was not declared in this scope)

**Comment by levy** [comment]
Thanks for bisecting, I'll check this.

**Comment by levy** [comment]
This crash is fixed by moving some initialization code to an earlier stage. Unfortunately another regression popped up related to the outgoing interface. So I'm not closing this issue yet.

**Comment by levy** [comment]
I added a separate issue at #483 for the new bug. I close this, because the crash is fixed.
